

services:
  
  notesappflask_v1.0:
    image: notesappflask_v1.0
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - 5000:5000
    networks:
      - existing_db_bridge

networks:
  existing_db_bridge:
    external:
      name: app_db_bridge