"""empty message

Revision ID: 919f7812e528
Revises: 
Create Date: 2025-01-20 00:48:23.551282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '919f7812e528'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.execute(r"CREATE SEQUENCE notes_app_users_id_seq START WITH 1 INCREMENT BY 1")
    op.execute(r"CREATE SEQUENCE notes_app_notes_id_seq START WITH 1 INCREMENT BY 1")
    op.execute(r"CREATE SEQUENCE notes_app_api_access_id_seq START WITH 1 INCREMENT BY 1")
    
    op.create_table('TBL_NOTES_APP_API_ACCESS',
    sa.Column('id', sa.Integer(), server_default=sa.text('notes_app_api_access_id_seq.nextval'), nullable=False),
    sa.Column('client_name', sa.String(length=80), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('is_locked', sa.String(length=1), nullable=False),
    sa.Column('created_at', sa.DATE(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('TBL_NOTES_APP_USERS',
    sa.Column('id', sa.Integer(), server_default=sa.text('notes_app_users_id_seq.nextval'), nullable=False),
    sa.Column('username', sa.String(length=256), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('TBL_NOTES_APP_NOTES',
    sa.Column('id', sa.Integer(), server_default=sa.text('notes_app_notes_id_seq.nextval'), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('content', sa.String(length=256), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DATE(), nullable=False),
    sa.Column('updated_at', sa.DATE(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['TBL_NOTES_APP_USERS.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###


    op.drop_table('TBL_NOTES_APP_NOTES')
    op.drop_table('TBL_NOTES_APP_USERS')
    op.drop_table('TBL_NOTES_APP_API_ACCESS')

    op.execute(r"DROP SEQUENCE notes_app_users_id_seq ")
    op.execute(r"DROP SEQUENCE notes_app_notes_id_seq ")
    op.execute(r"DROP SEQUENCE notes_app_api_access_id_seq")
    # ### end Alembic commands ###
